# Generated by Django 6.0.7 on 2026-07-19 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoiNapXu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_goi', models.CharField(blank=True, max_length=100, null=True)),
                ('so_xu', models.IntegerField(blank=True, null=True)),
                ('xu_tang_kem', models.IntegerField(default=0)),
                ('gia_tien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gói nạp xu',
                'verbose_name_plural': 'Gói nạp xu',
                'db_table': 'goi_nap_xu',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mat_khau_hash', models.CharField(max_length=255)),
                ('api_token', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('so_du_xu', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'nguoi_dung',
            },
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('tac_gia', models.CharField(max_length=150)),
                ('diem_danh_gia', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('so_chuong', models.IntegerField(default=0)),
                ('luot_doc', models.IntegerField(default=0)),
                ('trang_thai', models.CharField(default='Đang ra', max_length=50)),
                ('anh_bia_url', models.CharField(max_length=512)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'db_table': 'sach',
            },
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_the_loai', models.CharField(max_length=100, unique=True)),
                ('duong_dan_slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'db_table': 'the_loai',
            },
        ),
        migrations.CreateModel(
            name='LichSuGiaoDich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_giao_dich_cong', models.CharField(blank=True, max_length=100, null=True)),
                ('phuong_thuc', models.CharField(blank=True, max_length=50, null=True)),
                ('trang_thai', models.CharField(default='Chờ xử lý', max_length=50)),
                ('ngay_giao_dich', models.DateTimeField(auto_now_add=True)),
                ('goi_nap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.goinapxu')),
                ('nguoi_dung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nguoidung')),
            ],
            options={
                'verbose_name': 'Lịch sử giao dịch',
                'verbose_name_plural': 'Lịch sử giao dịch',
                'db_table': 'lich_su_giao_dich',
            },
        ),
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(blank=True, max_length=255, null=True)),
                ('so_thu_tu_chuong', models.IntegerField(blank=True, null=True)),
                ('co_khoa', models.BooleanField(default=False)),
                ('xu_yeu_cau', models.IntegerField(default=0)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuongs', to='api.sach')),
            ],
            options={
                'verbose_name': 'Chương',
                'verbose_name_plural': 'Chương',
                'db_table': 'chuong',
            },
        ),
        migrations.CreateModel(
            name='SachTheLoai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gan', models.DateTimeField(auto_now_add=True)),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sach')),
                ('the_loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theloai')),
            ],
            options={
                'verbose_name': 'Sách - Thể loại',
                'verbose_name_plural': 'Sách - Thể loại',
                'db_table': 'sach_the_loai',
                'unique_together': {('sach', 'the_loai')},
            },
        ),
        migrations.AddField(
            model_name='sach',
            name='the_loai',
            field=models.ManyToManyField(related_name='saches', through='api.SachTheLoai', to='api.theloai'),
        ),
        migrations.CreateModel(
            name='ChuongDaMoKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xu_da_tra', models.IntegerField(blank=True, null=True)),
                ('ngay_mo_khoa', models.DateTimeField(auto_now_add=True)),
                ('chuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chuong')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nguoidung')),
            ],
            options={
                'verbose_name': 'Chương đã mở khóa',
                'verbose_name_plural': 'Chương đã mở khóa',
                'db_table': 'chuong_da_mo_khoa',
                'unique_together': {('nguoi_dung', 'chuong')},
            },
        ),
        migrations.CreateModel(
            name='SachYeuThich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nguoidung')),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sach')),
            ],
            options={
                'verbose_name': 'Sách yêu thích',
                'verbose_name_plural': 'Sách yêu thích',
                'db_table': 'sach_yeu_thich',
                'unique_together': {('nguoi_dung', 'sach')},
            },
        ),
    ]
