# Generated by Django 6.0.7 on 2026-08-03 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LichSuDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_doc', models.DateTimeField(auto_now=True)),
                ('chuong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chuong')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nguoidung')),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sach')),
            ],
            options={
                'verbose_name': 'Lịch sử đọc',
                'verbose_name_plural': 'Lịch sử đọc',
                'db_table': 'lich_su_doc',
                'unique_together': {('nguoi_dung', 'sach')},
            },
        ),
    ]
