# Generated by Django 6.0.7 on 2026-08-04 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nguoidung_is_vip_lichsudoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='trang_thai',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='ThanhVienVip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kich_hoat', models.DateTimeField(auto_now_add=True)),
                ('ngay_het_han', models.DateTimeField()),
                ('xu_da_tra', models.IntegerField(default=1000)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_subscriptions', to='api.nguoidung')),
            ],
            options={
                'verbose_name': 'Thành viên VIP',
                'verbose_name_plural': 'Thành viên VIP',
                'db_table': 'thanh_vien_vip',
            },
        ),
    ]
