# Generated by Django 6.0.7 on 2026-08-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nguoidung_trang_thai_nguoidung_vai_tro_thanhvienvip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.nguoidung')),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.sach')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'db_table': 'review',
            },
        ),
    ]
