# Generated by Django 6.0.7 on 2026-09-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='push_token',
            field=models.CharField(blank=True, help_text='Expo Push Token để gửi thông báo đẩy đến thiết bị.', max_length=255, null=True),
        ),
    ]
